### ISSUE TITLE
DOC: Scipy site certificate expired on 16/11/2023

### ISSUE THREAD

**Issue by lucyleeow** [scipy/docs.scipy.org#80] opened 2023-11-16 02:11 UTC
### Issue with current documentation:

Scipy site certificate expired on 16/11/2023

![Screenshot_2023-11-16_13-10-13](https://github.com/scipy/scipy/assets/23182829/f5207675-ba08-4a24-8a75-9de1102d027b)

**Comment by tylerjereddy** [comment] 2023-11-16 02:22
I've transferred this issue over to the docs.scipy.org repo.

I also sent an email to our latest contact at Enthought (server admins) and cc'd Ralf on it.

**Comment by maxnoe** [comment] 2023-11-16 15:58
Seems to be fixed now: https://docs.scipy.org/doc/scipy/

**Comment by tylerjereddy** [comment] 2023-11-16 16:33
Yes, Enthought team confirmed fix.

**Comment by mdhaber** [comment] 2023-12-06 22:27
@tylerjereddy I think there is still a problem with https://projects.scipy.org/scipylib/mailing-lists.html. Can you check in with Enthought about that?

**Closed as completed** 2023-12-06 22:27 UTC

**Comment by tylerjereddy** [comment] 2023-12-06 23:29
Ok, I've followed up with Enthought in case that's under their remit (I'm not sure that it is, but I asked...).

**Comment by dpinte** [comment] 2023-12-07 11:05
The issue has been fixed. There was no vhost for projects.scipy.org on Apache and thus it was using the default and expired certificate. The certificate is now managed by LetsEncrypt and will auto-renew.

**Comment by tylerjereddy** [comment] 2023-12-07 16:43
Thanks @dpinte!
